apiVersion: v1
kind: PersistentVolume
metadata:
  name: big
spec:
  capacity:
    storage: 108000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0785e49e590fca7f5
    volumeAttributes:
      dnsname: fs-0785e49e590fca7f5.fsx.us-east-1.amazonaws.com
      mountname: big
  storageClassName: sc-neox
