apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: {{ name }}
  version: "1.19"
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1d"]

iam:
  withOIDC: true

addons:
  - name: vpc-cni
    version: v1.7.10-eksbuild.1  

managedNodeGroups:
  - name: cluster
    instanceType: {{ instance_type }}
    instancePrefix: cluster-worker
    privateNetworking: true
    availabilityZones: ["us-east-1d"]
    efaEnabled: true
    #minSize: {{ nodes }}
    desiredCapacity: {{ nodes }}
    #maxSize: {{ nodes }}
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: false
        ebs: true
        fsx: true
        cloudWatch: true
