apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ storage_class_name }}
mountOptions:
- flock
parameters:
  # s3ImportPath: {{ s3_import_path }}
  # s3ExportPath: {{ s3_export_path }}
  securityGroupIds: {{ security_group_id }}
  subnetId: {{ subnet_id }}
provisioner: fsx.csi.aws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ persistent_volume_claim_name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ storage_size }}
  storageClassName: {{ storage_class_name }}
