apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-sc
mountOptions:
- flock
parameters:
  s3ExportPath: s3://eai-neox/export
  s3ImportPath: s3://eao-neox/
  securityGroupIds: sg-00da9d8959034c8d6
  subnetId: subnet-0e00b9e3e1133dd56
provisioner: fsx.csi.aws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3.6Ti
  storageClassName: fsx-sc
