apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neox
spec:
  replicas: {{ nodes }}
  serviceName: {{ name }}
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: {{ name }}
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: neox
        tty: true
        image: {{ docker_image }}
        env:
        - name: FI_PROVIDER
          value: efa
        - name: FI_EFA_USE_DEVICE_RDMA
          value: '1'
        - name: NCCL_DEBUG
          value: info
        - name: RDMAV_FORK_SAFE
          value: '1'
        - name: LD_PRELOAD
          value: /opt/nccl/build/lib/libnccl.so
        ports:
          - name: sshd
            containerPort: 22
            protocol: TCP
        resources:
          requests:
            hugepages-2Mi: 5120Mi
            cpu: "90"
            memory: 500Gi
            nvidia.com/gpu: "8"
            vpc.amazonaws.com/efa: 4
          limits:
            hugepages-2Mi: 5120Mi
            cpu: "90"
            memory: 500Gi
            nvidia.com/gpu: "8"
            vpc.amazonaws.com/efa: 4
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - name: secret-volume
            readOnly: true
            mountPath: "/secrets"
        {% for mount in mounts %}
          - mountPath: {{ mount['path'] }}
            name: {{ mount['name'] }}
        {% endfor %}
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/bash", "/secrets/post_start_script.sh" ]
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: secret-volume
          secret:
            secretName: {{ secret_name }}
            defaultMode: 0777
      {% for mount in mounts %}
        - name: {{ mount['name'] }}
          persistentVolumeClaim:
            claimName: {{ mount['pvc_name'] }}
      {% endfor %}
      restartPolicy: Always

